# Form implementation generated from reading ui file 'c:\Users\juane\Desktop\emes_despachos\client\gui.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(920, 650)
        self.connectButton = QtWidgets.QPushButton(Form)
        self.connectButton.setGeometry(QtCore.QRect(40, 40, 380, 25))
        self.connectButton.setStyleSheet("QPushButton {\n"
"     background-color: rgb(0, 150, 214);\n"
"    color: rgb(255, 255, 255);    \n"
"    border-style: solid;\n"
"    border-width:1px;\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(141, 206, 233);\n"
"}")
        self.connectButton.setObjectName("connectButton")
        self.reportPartialButton = QtWidgets.QPushButton(Form)
        self.reportPartialButton.setGeometry(QtCore.QRect(40, 110, 190, 25))
        self.reportPartialButton.setStyleSheet("QPushButton {\n"
"     background-color: rgb(0, 150, 214);\n"
"    color: rgb(255, 255, 255);    \n"
"    border-style: solid;\n"
"    border-width:1px;\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(141, 206, 233);\n"
"}")
        self.reportPartialButton.setObjectName("reportPartialButton")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(40, 270, 125, 20))
        self.label.setObjectName("label")
        self.editURLDB = QtWidgets.QLineEdit(Form)
        self.editURLDB.setEnabled(True)
        self.editURLDB.setGeometry(QtCore.QRect(220, 270, 650, 22))
        self.editURLDB.setInputMask("")
        self.editURLDB.setText("")
        self.editURLDB.setMaxLength(32767)
        self.editURLDB.setObjectName("editURLDB")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(40, 330, 125, 16))
        self.label_2.setObjectName("label_2")
        self.editIDPlanillas = QtWidgets.QLineEdit(Form)
        self.editIDPlanillas.setGeometry(QtCore.QRect(220, 330, 650, 22))
        self.editIDPlanillas.setObjectName("editIDPlanillas")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(40, 390, 125, 16))
        self.label_3.setObjectName("label_3")
        self.editIDRemisiones = QtWidgets.QLineEdit(Form)
        self.editIDRemisiones.setGeometry(QtCore.QRect(220, 390, 650, 22))
        self.editIDRemisiones.setObjectName("editIDRemisiones")
        self.editJsonPath = QtWidgets.QLineEdit(Form)
        self.editJsonPath.setGeometry(QtCore.QRect(220, 450, 650, 22))
        self.editJsonPath.setObjectName("editJsonPath")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(40, 450, 125, 16))
        self.label_4.setObjectName("label_4")
        self.editVarsButton = QtWidgets.QPushButton(Form)
        self.editVarsButton.setGeometry(QtCore.QRect(40, 580, 831, 25))
        self.editVarsButton.setStyleSheet("QPushButton {\n"
"     background-color: rgb(141, 206, 233);\n"
"    color: rgb(255, 255, 255);    \n"
"    border-style: solid;\n"
"    border-width:1px;\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(189, 223, 238);\n"
"}")
        self.editVarsButton.setObjectName("editVarsButton")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(0, 0, 920, 650))
        self.label_5.setStyleSheet("border-image: url(:/cct/logo_emes.png);\n"
"background-color: rgb(255, 255, 255);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.editJsonPathGS = QtWidgets.QLineEdit(Form)
        self.editJsonPathGS.setGeometry(QtCore.QRect(220, 510, 650, 22))
        self.editJsonPathGS.setObjectName("editJsonPathGS")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(40, 510, 125, 16))
        self.label_6.setObjectName("label_6")
        self.distpachesReportButton = QtWidgets.QPushButton(Form)
        self.distpachesReportButton.setGeometry(QtCore.QRect(40, 190, 190, 25))
        self.distpachesReportButton.setStyleSheet("QPushButton {\n"
"     background-color: rgb(0, 150, 214);\n"
"    color: rgb(255, 255, 255);    \n"
"    border-style: solid;\n"
"    border-width:1px;\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(141, 206, 233);\n"
"}")
        self.distpachesReportButton.setObjectName("distpachesReportButton")
        self.dateEditTreasury = QtWidgets.QDateEdit(Form)
        self.dateEditTreasury.setGeometry(QtCore.QRect(260, 110, 160, 22))
        self.dateEditTreasury.setAcceptDrops(False)
        self.dateEditTreasury.setAutoFillBackground(False)
        self.dateEditTreasury.setCalendarPopup(True)
        self.dateEditTreasury.setObjectName("dateEditTreasury")
        self.dateEditDispatches = QtWidgets.QDateEdit(Form)
        self.dateEditDispatches.setGeometry(QtCore.QRect(260, 190, 160, 22))
        self.dateEditDispatches.setCalendarPopup(True)
        self.dateEditDispatches.setObjectName("dateEditDispatches")
        self.label_5.raise_()
        self.connectButton.raise_()
        self.reportPartialButton.raise_()
        self.label.raise_()
        self.editURLDB.raise_()
        self.label_2.raise_()
        self.editIDPlanillas.raise_()
        self.label_3.raise_()
        self.editIDRemisiones.raise_()
        self.editJsonPath.raise_()
        self.label_4.raise_()
        self.editVarsButton.raise_()
        self.editJsonPathGS.raise_()
        self.label_6.raise_()
        self.distpachesReportButton.raise_()
        self.dateEditTreasury.raise_()
        self.dateEditDispatches.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.connectButton.setText(_translate("Form", "Conectar"))
        self.reportPartialButton.setText(_translate("Form", "Informe Tesorería"))
        self.label.setText(_translate("Form", "URL Database"))
        self.label_2.setText(_translate("Form", "Folder ID Planillas"))
        self.label_3.setText(_translate("Form", "Folder ID Remisiones"))
        self.label_4.setText(_translate("Form", "JSON Database path"))
        self.editVarsButton.setText(_translate("Form", "Editar variables"))
        self.label_6.setText(_translate("Form", "JSON Gspread path"))
        self.distpachesReportButton.setText(_translate("Form", "Informe Despachos"))
        self.dateEditTreasury.setDisplayFormat(_translate("Form", "yyyy-MM-dd"))
        self.dateEditDispatches.setDisplayFormat(_translate("Form", "yyyy-MM-dd"))
